
(define kernel-table
  (make-primitive-table
   *
   +
   -
   /
   <
   <=
   =
   >
   >=
   quotient
   remainder
   abort-current-continuation
   abs
   absolute-path?
   add1
   always-evt
   andmap
   append
   apply
   arithmetic-shift
   arity-at-least
   arity-at-least-value
   arity-at-least?
   assoc
   assq
   assv
   bitwise-ior
   boolean?
   box
   box-cas!
   box-immutable
   box?
   break-enabled-key
   build-path
   byte-pregexp
   byte-pregexp?
   byte-regexp
   byte-regexp?
   byte?
   bytes
   bytes->path
   bytes->path-element
   bytes->string/locale
   bytes->string/utf-8
   bytes-append
   bytes-length
   bytes-ref
   bytes<?
   bytes=?
   bytes?
   caadr
   cache-configuration
   call/cc
   call-with-continuation-barrier
   call-with-continuation-prompt
   call-with-current-continuation
   call-with-escape-continuation
   call-with-semaphore
   call-with-values
   ceiling
   channel?
   channel-put-evt
   chaperone-of?
   chaperone-procedure
   chaperone-procedure*
   chaperone-struct
   char->integer
   char-alphabetic?
   char-numeric?
   char-whitespace?
   char<=?
   char<?
   char=?
   char>=?
   char>?
   char?
   check-for-break
   checked-procedure-check-and-extract
   cleanse-path
   close-input-port
   compile-enforce-module-constants
   complete-path?
   continuation-mark-set-first
   continuation-prompt-available?
   current-code-inspector
   current-compile
   current-compiled-file-roots
   current-continuation-marks
   current-directory
   current-environment-variables
   current-eval
   current-input-port
   current-inspector
   current-library-collection-links
   current-library-collection-paths
   current-load
   current-load-extension
   current-load-relative-directory
   current-load/use-compiled
   current-logger
   current-output-port
   current-print
   current-prompt-read
   current-read-interaction
   current-thread
   datum-intern-literal
   default-continuation-prompt-tag
   directory-exists?
   directory-list
   display
   dynamic-wind
   environment-variables-ref
   environment-variables-set!
   eof
   eof-object?
   ephemeron-value
   eq-hash-code
   eq?
   equal-hash-code
   equal?
   eqv?
   error
   error-print-source-location
   eval-jit-enabled
   exact-integer?
   exact-nonnegative-integer?
   exact-positive-integer?
   exact?
   exact->inexact
   exception-handler-key
   exn-continuation-marks
   exn-message
   exn?
   expand-user-path
   expt
   extend-parameterization
   file-exists?
   file-or-directory-modify-seconds
   file-position
   filesystem-change-evt
   filesystem-change-evt-cancel
   find-system-path
   fixnum?
   flonum?
   floor
   flvector-length
   flvector-set!
   flvector?
   for-each
   format
   fprintf
   fxvector-length
   fxvector-set!
   fxvector?
   gensym
   hash
   hash-clear!
   hash-copy
   hash-count
   hash-eq?
   hash-eqv?
   hash-for-each
   hash-iterate-first
   hash-iterate-key
   hash-iterate-key+value
   hash-iterate-next
   hash-iterate-value
   hash-keys-subset?
   hash-map
   hash-ref
   hash-remove
   hash-remove!
   hash-set
   hash-set!
   hash?
   hasheq
   hasheqv
   immutable?
   impersonate-procedure
   impersonate-procedure*
   impersonate-struct
   impersonator-of?
   impersonator-property?
   inexact?
   inexact->exact
   input-port?
   inspector-superior?
   inspector?
   integer->char
   integer->integer-bytes
   integer?
   length
   list
   list*
   list->string
   list->vector
   list-ref
   list-tail
   list?
   load
   load-extension
   load-on-demand-enabled
   logger?
   log-level?
   log-message
   make-arity-at-least
   make-bytes
   make-continuation-prompt-tag
   make-ephemeron
   make-flvector
   make-fxvector
   make-hash
   make-hash-placeholder
   make-hasheq
   make-hasheq-placeholder
   make-hasheqv
   make-hasheqv-placeholder
   make-immutable-hash
   make-immutable-hasheq
   make-immutable-hasheqv
   make-inspector
   make-parameter
   make-placeholder
   make-prefab-struct
   make-reader-graph
   make-semaphore
   make-string
   make-struct-field-accessor
   make-struct-field-mutator
   make-struct-type
   make-struct-type-property
   make-thread-cell
   make-vector
   make-weak-box
   make-weak-hash
   make-weak-hasheq
   map
   max
   min
   modulo
   negative?
   newline
   not
   null
   null?
   number->string
   number?
   object-name
   open-input-bytes
   open-input-file
   ormap
   output-port?
   parameterization?
   parameterization-key
   path->bytes
   path->complete-path
   path->string
   path-convention-type
   path-element->bytes
   path-for-some-system?
   path?
   peek-byte
   peek-bytes
   peek-char-or-special
   placeholder-set!
   port-count-lines!
   port-next-location
   port-read-handler
   positive?
   prefab-key->struct-type
   prefab-key?
   prefab-struct-key
   pregexp
   pregexp?
   primitive-table
   print
   procedure-arity
   procedure-arity-includes?
   procedure-extract-target
   procedure-reduce-arity
   procedure-rename
   procedure->method
   procedure?
   prop:arity-string
   prop:checked-procedure
   prop:custom-write
   prop:equal+hash
   prop:evt
   prop:impersonator-of
   prop:incomplete-arity
   prop:method-arity-error
   prop:procedure
   raise
   read-accept-bar-quote
   read-byte
   read-bytes
   read-case-sensitive
   read-char
   read-char-or-special
   read-decimal-as-inexact
   read-on-demand-source
   real?
   regexp
   regexp-match
   regexp-match-positions
   regexp-match?
   regexp-replace
   regexp-replace*
   regexp?
   relative-path?
   reparameterize
   resolve-path
   reverse
   semaphore-peek-evt
   semaphore-post
   set-box!
   simplify-path
   split-path
   string
   string->bytes/latin-1
   string->bytes/locale
   string->bytes/utf-8
   string->immutable-string
   string->number
   string->path
   string->symbol
   string->uninterned-symbol
   string->unreadable-symbol
   string-append
   string-ci<=?
   string-ci<?
   string-ci>=?
   string-ci>?
   string-copy!
   string-foldcase
   string-length
   string-locale-downcase
   string-ref
   string-set!
   string<=?
   string<?
   string=?
   string>=?
   string>?
   string?
   struct->vector
   struct-type?
   struct?
   struct:arity-at-least
   sub1
   subbytes
   substring
   symbol->string
   symbol-interned?
   symbol<?
   symbol?
   sync
   sync/timeout
   system-library-subpath
   system-path-convention-type
   system-type
   thread-send
   thread-wait
   unbox
   use-collection-link-paths
   use-compiled-file-paths
   use-user-specific-search-paths
   values
   vector
   vector->immutable-vector
   vector->list
   vector-copy!
   vector-immutable
   vector-length
   vector-ref
   vector-set!
   vector?
   version
   void
   void?
   weak-box-value
   with-input-from-file
   wrap-evt
   write
   write-string
   zero?
   
   keyword<?
   string->keyword
   keyword->string
   keyword?

   cons pair?
   car cdr
   caar cadr cdar cddr
   caaar caadr cadar caddr cdaar cdadr cddar cdddr
   caaaar caaadr caadar caaddr cadaar cadadr caddar cadddr
   cdaaar cdaadr cdadar cdaddr cddaar cddadr cdddar cddddr

   mpair?
   mcons
   mcar
   mcdr
   set-mcar!
   set-mcdr!

   raise-argument-error
   raise-arguments-error
   raise-result-error
   raise-mismatch-error
   raise-range-error

   struct:exn exn exn? exn-message exn-continuation-marks
   struct:exn:break exn:break exn:break? exn:break-continuation
   struct:exn:fail exn:fail exn:fail?
   struct:exn:fail:contract exn:fail:contract exn:fail:contract?
   struct:exn:fail:contract:variable exn:fail:contract:variable exn:fail:contract:variable?
   struct:exn:fail:filesystem exn:fail:filesystem exn:fail:filesystem?
   struct:exn:fail:read exn:fail:read exn:fail:read? exn:fail:read-srclocs
   struct:exn:fail:read:eof exn:fail:read:eof exn:fail:read:eof?
   struct:exn:fail:read:non-char exn:fail:read:non-char exn:fail:read:non-char?

   prop:exn:srclocs exn:srclocs? exn:srclocs-accessor

   struct:srcloc srcloc srcloc?
   srcloc-source srcloc-line srcloc-column srcloc-position srcloc-span
   srcloc->string

   [host:datum->syntax datum->syntax]
   [host:syntax->datum syntax->datum]
   syntax-property-symbol-keys
   syntax-property syntax-span syntax-position syntax-column
   syntax-line syntax-source syntax-e syntax?))
