#lang racket/base
(require racket/include
         (only-in '#%kernel open-input-file))

(provide (rename-out
          (1/peek-bytes! peek-bytes!)
          (1/peek-byte peek-byte)
          (1/write-bytes-avail write-bytes-avail)
          (1/open-input-file open-input-file)
          (1/write-bytes-avail* write-bytes-avail*)
          (1/bytes->string/locale bytes->string/locale)
          (1/read-bytes-avail!* read-bytes-avail!*)
          (1/make-pipe make-pipe)
          (1/write-string write-string)
          (1/open-input-bytes open-input-bytes)
          (1/read-string! read-string!)
          (1/string->bytes/latin-1 string->bytes/latin-1)
          (1/bytes->string/utf-8 bytes->string/utf-8)
          (1/string->bytes/utf-8 string->bytes/utf-8)
          (1/string->bytes/locale string->bytes/locale)
          (1/read-bytes read-bytes)
          (pipe-input-port? pipe-input-port?)
          (1/peek-char peek-char)
          (1/bytes-utf-8-length bytes-utf-8-length)
          (1/peek-string peek-string)
          (1/write-bytes-avail/enable-break write-bytes-avail/enable-break)
          (1/read-char read-char)
          (1/make-output-port make-output-port)
          (1/close-input-port close-input-port)
          (1/write-bytes write-bytes)
          (1/read-bytes-avail! read-bytes-avail!)
          (1/peek-string! peek-string!)
          (1/string-utf-8-length string-utf-8-length)
          (pipe-output-port? pipe-output-port?)
          (1/read-byte read-byte)
          (1/make-input-port make-input-port)
          (1/port-next-location port-next-location)
          (1/read-string read-string)
          (1/bytes->string/latin-1 bytes->string/latin-1)
          (1/port-count-lines! port-count-lines!)
          (1/peek-bytes-avail! peek-bytes-avail!)
          (1/pipe-content-length pipe-content-length)
          (1/peek-bytes-avail!* peek-bytes-avail!*)
          (1/read-bytes! read-bytes!)
          (1/peek-bytes peek-bytes)
          (1/close-output-port close-output-port)))

(define-syntax-rule (linklet () (ex ...) body ...)
  (begin body ...))

(include "port.rktl")
